#!/usr/bin/env python3
"""Bundle interactive runtime for exported HTML embeds."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "export-bundle-source.js"

FILES = [
    ROOT / "js" / "utils.js",
    ROOT / "js" / "modals.js",
    ROOT / "js" / "animations.js",
    ROOT / "js" / "sections.js",
    ROOT / "js" / "passing-splits.js",
    ROOT / "js" / "grading-profile.js",
    ROOT / "js" / "interception-luck.js",
    ROOT / "js" / "target-depth.js",
    ROOT / "js" / "accuracy-depth.js",
    ROOT / "js" / "target-map-api.js",
    ROOT / "js" / "target-map.js",
    ROOT / "js" / "route-tree-api.js",
    ROOT / "js" / "route-tree.js",
    ROOT / "js" / "export-boot.js",
]


def main():
    parts = []
    for path in FILES:
        if not path.is_file():
            raise FileNotFoundError(f"Missing export runtime file: {path}")
        parts.append(path.read_text(encoding="utf-8"))

    bundle = "\n".join(parts)
    payload = json.dumps(bundle, ensure_ascii=False)
    OUT.write_text(
        "/** Auto-generated by scripts/build-export-bundle.py — do not edit by hand. */\n"
        f"window.QbAnnualExportBundleSource = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
