#!/usr/bin/env python3
"""Bundle CSV files into js/bundled-data.js for file:// usage."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "bundled-data.js"

FILES = {
    "passingSummaryText": [
        ROOT / "passing-summary-23-25.csv",
        ROOT / "passing summary 23-25.csv",
    ],
    "gameGradeFeedText": [ROOT / "game_grade_feed.csv"],
    "gradeDistributionFeedText": [ROOT / "grade-distribution.csv"],
    "opponentsFeedText": [ROOT / "opponents.csv"],
    "gradingProfileFeedText": [
        ROOT / "grading profile.csv",
        ROOT / "grading-profile.csv",
    ],
    "stableUnstableFeedText": [
        ROOT / "Stable and unstable.csv",
        ROOT / "stable-unstable.csv",
    ],
    "passingPressureFeedText": [ROOT / "passing_pressure.csv"],
    "passingConceptFeedText": [ROOT / "passing_concept.csv"],
    "timeInPocketFeedText": [ROOT / "time_in_pocket.csv"],
    "intLuckFeedText": [ROOT / "int-luck-season.csv"],
    "passingDepthFeedText": [ROOT / "passing_depth.csv"],
    "accuracyByDepthFeedText": [ROOT / "accuracy-by-depth.csv"],
    "generalAccuracyFeedText": [
        ROOT / "general-accuracy.csv",
        ROOT / "General accuracy.csv",
    ],
    "qbAccuracyFeedText": [
        ROOT / "QB Accuracy.csv",
        ROOT / "qb-accuracy.csv",
    ],
    "incompletionRatesFeedText": [
        ROOT / "Incompletion rates.csv",
        ROOT / "incompletion-rates.csv",
    ],
    "qbAlignmentFeedText": [
        ROOT / "qb-alignment.csv",
        ROOT / "QB Alignment.csv",
    ],
    "allowedPressureFeedText": [
        ROOT / "passing_allowed_pressure.csv",
    ],
    "clutchFeedText": [
        ROOT / "clutch-2025.csv",
    ],
    "routeDataFeedText": [
        ROOT / "route-data.csv",
        ROOT / "Route data.csv",
    ],
    "targetMapFeedText": [ROOT / "target-map.csv"],
    "epaSeasonFeedText": [ROOT / "epa-per-play-season.csv"],
    "epaCareerFeedText": [ROOT / "epa-per-play-career.csv"],
    "warSeasonFeedText": [ROOT / "qb-war-season.csv"],
    "rushingSummaryFeedText": [ROOT / "rushing_summary.csv"],
    "passingGradesSituationFeedText": [
        ROOT / "Passing grades by situation.csv",
        ROOT / "passing-grades-by-situation.csv",
    ],
    "passingGradesReadsFeedText": [ROOT / "Reads.csv", ROOT / "reads.csv"],
    "passingGradesCoverageFeedText": [
        ROOT / "Throws vs. coverage.csv",
        ROOT / "throws-vs-coverage.csv",
    ],
    "targetAlignmentFeedText": [ROOT / "target-alignment.csv"],
    "throwTypeFeedText": [ROOT / "throw-type.csv"],
}

def read_first(paths):
    for path in paths:
        if path.is_file():
            return path.read_text(encoding="utf-8-sig")
    raise FileNotFoundError(f"No file found for: {paths}")

def main():
    bundle = {key: read_first(paths) for key, paths in FILES.items()}
    payload = json.dumps(bundle, ensure_ascii=False)
    OUT.write_text(
        "/** Auto-generated by scripts/bundle-data.py — do not edit by hand. */\n"
        f"window.QbAnnualBundledData = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size:,} bytes)")

    export_script = ROOT / "scripts" / "build-export-bundle.py"
    if export_script.is_file():
        import subprocess
        subprocess.run(["python3", str(export_script)], check=True)

if __name__ == "__main__":
    main()
